# Generated by Django 3.2.13 on 2022-05-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='expiredate',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='uploadPDF',
            new_name='upload_pdf',
        ),
    ]
