# Generated by Django 3.2.13 on 2022-04-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExerciseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uploadPDF',
            field=models.FileField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
