# Generated by Django 3.2.13 on 2022-04-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExerciseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Classroom',
            new_name='classroom',
        ),
    ]
