# Generated by Django 3.2.13 on 2022-04-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExerciseApp', '0002_exercise_uploadpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='filePDF',
        ),
    ]
