# Generated by Django 3.2.13 on 2022-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExerciseApp', '0003_remove_exercise_filepdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='uploadPDF',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
