# Generated by Django 3.2.13 on 2022-04-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-Title']},
        ),
    ]
