# Generated by Django 3.2.13 on 2022-04-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
    ]
