# Generated by Django 3.2.13 on 2022-04-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentApp', '0002_auto_20220415_1553'),
        ('ExerciseApp', '0004_alter_exercise_uploadpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('uploadPDF', models.FileField(null=True, upload_to='uploads/')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExerciseApp.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
