# Generated by Django 3.2.13 on 2022-05-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='uploadPDF',
            new_name='uploadpdf',
        ),
    ]
