# Generated by Django 3.2.13 on 2022-04-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='semat',
            field=models.CharField(choices=[('Studernt', 'Studernt')], max_length=8, null=True),
        ),
    ]
