# Generated by Django 3.2.13 on 2022-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20220419_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semat',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Studernt')], max_length=8, null=True),
        ),
    ]
