# Generated by Django 3.2.13 on 2022-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_semat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semat',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student')], max_length=8, null=True),
        ),
    ]
