# Generated by Django 3.2.13 on 2022-04-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_user_semat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
