# Generated by Django 3.2.13 on 2022-05-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_user_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='semat',
            new_name='post',
        ),
    ]
