# Generated by Django 3.2.13 on 2022-04-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='UserName',
        ),
    ]
