# Generated by Django 3.2.13 on 2022-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
        ('ClassroomApp', '0002_auto_20220414_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='StudentApp.Student'),
        ),
        migrations.DeleteModel(
            name='ClassroomStudents',
        ),
    ]
