# Generated by Django 3.2.13 on 2022-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('NationalCode', models.IntegerField()),
                ('SchoolName', models.CharField(max_length=250)),
                ('UserName', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
