# Generated by Django 3.2.13 on 2022-04-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('NationalCode', models.IntegerField()),
                ('SchoolName', models.CharField(max_length=250)),
                ('UserName', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.course')),
            ],
        ),
    ]
