# Generated by Django 3.2.13 on 2022-04-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='UserName',
        ),
    ]
