# Generated by Django 3.2.13 on 2022-04-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=4000)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.course')),
            ],
        ),
    ]
