# Generated by Django 3.2.13 on 2022-04-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Classroom',
            new_name='classroom',
        ),
    ]
